<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function findInOrderByMinPc() {
        $qb = $this->createQueryBuilder('g')
                ->leftJoin('g.minPc', 'pc')
                ->leftJoin('pc.cpu', 'cpu')
                ->leftJoin('pc.gpu', 'gpu')
                ->orderBy('cpu.score + gpu.score', 'ASC')
                ->getQuery();
        return $qb->getResult();
    }
}
